// This file only contains RPC-related message definitions.

edition = "2024";

package peregrine.internal.proto;

import "src/internal/control/message_internal.proto";

// static_assert(assumptions::kThereIsOnlyOnePairOfWrapperControlMessages);
message ReqMsg {
  oneof msg {
    PeerRequests peer_requests = 1;
    HostInfo host_info = 2;
    RdmaConnectRequest rdma_connect_req = 3;
    // Append new request types here.
  }
}

message RespMsg {
  oneof msg {
    HostInfo host_info = 1;
    PeerResponse peer_response = 2;
    RdmaConnectResponse rdma_connect_resp = 3;
    // Append new request types here.
  }
}

// ---------------------------------------------------------
// TODO: move the messages below to a message_internal.proto
// Out-of-band key exchange messages for TCP-over-PSP.
message PspKey {
  uint32 spi = 1;
  bytes key = 2;  // 16-byte raw AES session key
}

message PspKeyExchangeRequest {
  PspKey psp = 1;

  // Specifies the endpoint of the data plane listener.
  // Only required when server has multiple data plane listeners.
  Endpoint endpoint = 2;
}

message PspKeyExchangeResponse {
  PspKey psp = 1;
}
