// This file only contains RPC-related _internal_ message definitions.
// These messages must not appear in RPC service.proto.

edition = "2024";

package peregrine.internal.proto;

// See internal/base/hostinfo.h
// TODO: Consider unifying TCP data_plane_listeners and rdma_interfaces into a
// polymorphic DataPlaneEndpoint message.
message HostInfo {
  Endpoint control_plane_listener = 1;
  repeated Endpoint data_plane_listeners = 2;
  repeated RdmaNic rdma_nics = 3;
}

message PeerReq {
  HostInfo peer = 1;
  repeated Request reqs = 2;
}

// Response to PeerRequests containing resolved remote memory keys.
message PeerResp {
  repeated uint32 rkeys = 1;
}

message PspTcpReq {
  PspToken psp = 1;
  Endpoint peer_target = 2;
}

message PspTcpResp {
  PspToken psp = 1;
}

// Request to establish an RDMA Queue Pair connection with a remote peer.
message RdmaConnReq {
  HostInfo peer = 1;       // Initiator's host information
  string device_name = 2;  // Target device on remote host, e.g. "irdma0"
  uint32 qpn = 3;          // Initiator's local QP number
  bytes gid = 4;           // Initiator's local GID (16 bytes)
  uint32 psn = 5;          // Initiator's starting packet sequence number
  // Initiator's memory region rkey. Assumed static for channel lifetime, but
  // may change in the future to dynamic per-transfer resolution.
  uint32 rkey = 6;
}

// Response to RdmaConnectRequest containing the responder's QP parameters.
message RdmaConnResp {
  uint32 qpn = 1;  // Responder's assigned QP number
  bytes gid = 2;   // Responder's GID on that device (16 bytes)
  uint32 psn = 3;  // Responder's starting packet sequence number
  // Responder's memory region rkey. Assumed static for channel lifetime, but
  // may change in the future to dynamic per-transfer resolution.
  uint32 rkey = 4;
}

// -------------------------
// Common message components
// -------------------------

message Request {
  enum Op {
    INVALID = 0;
    READ = 1;   // Read from peer
    WRITE = 2;  // Write to peer
  }
  Op op = 1;         // operation type
  uint64 laddr = 2;  // address in this local process
  uint64 raddr = 3;  // address in the remote peer process
  uint64 len = 4;    // buffer length in bytes
  uint32 rkey = 5;   // remote memory region key (for RDMA)
}

message Endpoint {
  bytes ip_port = 1;  // e.g. "127.0.0.1:56789" or "[::1]:56789"
}

message PspToken {
  uint32 spi = 1;  // security parameter index
  uint32 gen = 2;  // generation
  bytes key = 3;   // 16 bytes
}

message RdmaNic {
  string name = 1;  // device name, e.g. "irdma0"
  bytes gid = 2;    // 16-byte RoCEv2 GID
  uint32 port = 3;  // physical port number on HCA (typically 1)
}
