// This file only contains RPC-related message definitions.

edition = "2024";

package peregrine.internal.proto;

// static_assert(assumptions::kTcpListenersOfControlAndDataPlanesAreSeparate);
// static_assert(assumptions::kThereIsOnlyOneWrapperControlMessageAtMost1KiB);
message ReqMsg {
  oneof msg {
    PeerRequests peer_requests = 1;
    HostInfo host_info = 2;
  }
}

message RespMsg {
  oneof msg {
    HostInfo host_info = 1;
  }
}

// Below are inner messages.
// ------------------------

message PeerRequests {
  HostInfo peer = 1;
  repeated Request requests = 2;
}

// See internal/base/hostinfo.h
message HostInfo {
  Endpoint control_plane_listener = 1;
  repeated Endpoint data_plane_listeners = 2;
}

// See internal/base/endpoint.h
message Endpoint {
  bytes ip_port = 1;  // e.g. "127.0.0.1:56789" or "[::1]:56789"
}

// See api/transport_types.h
message Request {
  enum Op {
    INVALID = 0;
    READ = 1;   // Read from peer
    WRITE = 2;  // Write to peer
  }
  Op op = 1;         // operation type
  uint64 laddr = 2;  // address in this local process
  uint64 raddr = 3;  // address in the remote peer process
  uint64 len = 4;    // buffer length in bytes
}
