// This file only contains RPC-related message definitions.

edition = "2024";

package peregrine.internal.proto;

import "src/internal/control/message_internal.proto";

// static_assert(assumptions::kThereIsOnlyOnePairOfWrapperControlMessages);
message ReqMsg {
  oneof msg {
    HostInfo host_info = 1;
    PeerReq peer_req = 2;
    PspTcpReq psp_tcp_req = 3;
    RdmaConnReq rdma_conn_req = 4;
    // Append new request types here.
  }
}

message RespMsg {
  oneof msg {
    HostInfo host_info = 1;
    PeerResp peer_resp = 2;
    PspTcpResp psp_tcp_resp = 3;
    RdmaConnResp rdma_conn_resp = 4;
    // Append new request types here.
  }
}
