load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//src/internal:internal_impl"])

cc_library(
    name = "types",
    hdrs = ["types.h"],
    deps = [
        "@abseil-cpp//absl/strings:string_view",
    ],
)
