namespace peregrine.internal.flatbuf;

// `ChunkHeader` is used to serialize `ChunkMetadata` in chunk.h.
// They must be kept in sync.
struct ChunkHeader {
  ver:uint32;  // Do not change the first field.

  // The following fields can change.
  // When they change, the `ver` field must be incremented in your serializer.
  handle:uint32;
  buffer:uint32;
  nchunks:uint32;
  index:uint32;
  size:uint32;
  addr:uint64;

  // Paddings to keep the header size always 64 bytes.
  padding0:uint64;
  padding1:uint64;
  padding2:uint64;
  padding3:uint64;
}
