namespace peregrine.internal.flatbuf;

// Do not change.
enum Constant:uint16 {
  MAGIC = 0x4750,  // 'PG' in little-endian order
}

// `flatbuf::ChunkHeader` has a fixed size of 64 bytes. It is used to serialize
// the in-memory struct `ChunkHeader` in chunk.h. They must be kept in sync.
struct ChunkHeader {
  // Two fixed fields. Do not change.
  magic:uint16;
  ver:uint16;

  // The following fields can change.
  // When they do, the `ver` field must be incremented in the new serializer.
  handle:uint32;
  reqid:uint32;
  nchunks:uint32;
  index:uint32;
  size:uint32;
  addr:uint64;

  // Paddings to keep the header size always 64 bytes.
  padding0:uint64;
  padding1:uint64;
  padding2:uint64;
  padding3:uint64;
}
